# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3adea2d82c50af960f4870179c22a903b9983f2da3c384790a3ca958c3a176a831f069e26369114aba1cf47811f45c244c809e284df1817db480a0b73c84738

test:
  secret_key_base: d52509c38f2ab89e2c8dfcdb7807a8283ba4509e338b17acbe7632f4253dc3edcee0e0d42f9832d6319cde80a37a1aeb941129333fc199f91474bcee175572a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 3163182705956d2f6786c6b97af49b2ec250997d8fb7bef8f7058dedad5b71a24f05a244e935e851f71e2c8d5b69befa4107eaab2330a4bccc477aaff1f47a9f
